# Generated by Django 5.2.7 on 2025-11-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelFeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing', models.CharField(max_length=10)),
                ('fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HostelMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(max_length=30)),
                ('lunch', models.CharField(max_length=50)),
                ('dinner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HostelPersonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.BigIntegerField()),
                ('father_name', models.CharField(max_length=20)),
                ('aadhar', models.BigIntegerField()),
                ('address', models.TextField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('room_no', models.IntegerField()),
                ('date_of_joining', models.DateField()),
            ],
        ),
    ]
