# Generated by Django 5.2.7 on 2025-11-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelmenu',
            name='day',
            field=models.CharField(default='monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='hostelpersondetails',
            name='photo',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
